import { ISingleData } from "./interfaces"

export const DATA: ISingleData[] = [
	{
		id: 1,
		title: "Bivio",
		date: "28th February 2022",
		url: "-Ht3t24LoGI",
		note: "5 days in Bivio, Val Surses, Switzerland. Ski touring and teaching Jahia how to ski...",
		keyword: ["Jahia", "Skiing", "Switzerland"],
		img: "bivio",
	},
	{
		id: 2,
		title: "Magic carpet",
		date: "22th February 2022",
		url: "n1wnVdfcyjc",
		note: "Savognin, GR Switzerland - February 2022. Stop to the magic carpet on the way to Bivio",
		keyword: ["Jahia", "Skiing", "Switzerland"],
		img: "savognin",
	},
	{
		id: 3,
		title: "Pizza",
		date: "21th February 2022",
		url: "ct7Khn4CVpI",
		note: "Premier Chasse Neige à Arvenbüel, Janvier 2022.",
		keyword: ["Jahia", "Skiing", "Switzerland"],
		img: "pizza",
	},
	{
		id: 4,
		title: "Prima",
		date: "24th January 2022",
		url: "DlkRE2wy-UY",
		note: "Un dimanche au col de la Faucille a skier avec la Prima - Janvier 2022",
		keyword: ["Jahia", "Skiing", "France"],
		img: "prima",
	},
	{
		id: 5,
		title: "First Skiing",
		date: "23th February 2022",
		url: "dSV8WS9o4Go",
		note: "Jahia First time on skis... Flumserberg December 2021",
		keyword: ["Jahia", "Skiing", "Switzerland"],
		img: "premier",
	},
	{
		id: 6,
		title: "Ticino & Lago Maggiore",
		date: "5th December 2021",
		url: "QGZY-yaOhw0",
		note: "September 2021 a few days in Ticino, Lago Maggiore and Lago di Lugano on the way to Rosalina de Mare",
		keyword: ["Jahia", "Beach", "Hiking", "Road Trip"],
		img: "ticino",
	},
	{
		id: 7,
		title: "Arosa & Langwies",
		date: "12th March 2021",
		url: "cTm9IzMmqnU",
		note: "3 days in Arosa, Grison, Switzerland  -  March 2021 - Ski touring to the Erzhornsattel via RamozHütte - Sledging 5km down from Heimeli Sapün to Langwies.",
		keyword: ["Jahia", "Skiing", "Sledging", "Switzerland"],
		img: "arosa",
	},
	{
		id: 8,
		title: "Flumserberg",
		date: "3rd December 2021",
		url: "Y__3AIMW90I",
		note: "Ski touring and sledging around Flumserberg, Switzerland.",
		keyword: ["Jahia", "Skiing", "Sledging", "Switzerland"],
		img: "flumserberg",
	},
	{
		id: 9,
		title: "Back 2 Switzerland",
		date: "15th May 2021",
		url: "XeUpJau2Yug",
		note: "Few days in Wengen 2020 between 2 waves of Corona",
		keyword: ["Jahia", "Hiking", "Switzerland"],
		img: "wengen",
	},
	{
		id: 10,
		title: "Heron Island",
		date: "24th October 2020",
		url: "Ljdqpz1rfDQ",
		note: "Heron Island Queensland Australia - Southern Great Barrier Reef - 5 days in paradise just relax and have fun, snorkeling and scuba diving all day long from sunrise to sunset. Including our best shoot of local marine wildlife Manta Ray, sharks, Tahitian ray, eagle ray, green turtles, shovel nose ray and more.",
		keyword: ["Jahia", "Snorkelling", "Beach", "Australia"],
		img: "heron",
	},
	{
		id: 11,
		title: "Birthday",
		date: "26th Avril 2020",
		url: "9QDanYLiHHE",
		note: "Happy Birthday Jahia : One year !!!",
		keyword: ["Jahia", "Birthday", "Australia"],
		img: "birthday",
	},
	{
		id: 12,
		title: "New Zealand",
		date: "22th April 2020",
		url: "Nw6IDY2yCkU",
		note: "2 weeks of Road Trip in New Zealand's North Island",
		keyword: ["Jahia", "Hiking", "Beach", "Road Trip"],
		img: "nz",
	},
	{
		id: 13,
		title: "Lord Howe Island",
		date: "27th March 2020",
		url: "v6iYDc1A36Q",
		note: "A few days in Lord Howe Island during Cyclone UESI - February 2020",
		keyword: ["Jahia", "Hiking", "Snorkelling", "Beach", "Australia"],
		img: "lord",
	},
	{
		id: 14,
		title: "Fraser Island",
		date: "26th March 2020",
		url: "B8p5I-gnMUs",
		note: "2 times 5 days of beach camping in FRASER ISLAND between December 2019 and January 2020.",
		keyword: ["Jahia", "Road Trip", "Beach", "Australia"],
		img: "fraser",
	},
	{
		id: 15,
		title: "Once upon a time",
		date: "1st April 2020",
		url: "rAXX7JCc3CQ",
		note: "A seed and 9 month later a birth notice ! ",
		keyword: ["Jahia", "Birthday", "Australia"],
		img: "birth",
	},
	{
		id: 16,
		title: "Brisbane's Clouds",
		date: "31st May 2019",
		url: "Oyhb5zb_esQ",
		note: "Timelapse of Brisbane's CBD from Balcony, shooted with Canon EOS 80D",
		keyword: ["Australia"],
		img: "brisbane",
	},
	{
		id: 17,
		title: "Brisbane to Cairns",
		date: "23th September 2018",
		url: "9LiGlRG5VXY",
		note: "Road trip between Brisbane and Cairns, Queensland, Australia, August 2018 : Whales watching in Harvey Bay, Sailing & Snorkeling in Whitsunday islands , Great Barrier Reef diving at the fish bowl (Briggs Reef)",
		keyword: ["Hiking", "Road Trip", "Snorkelling", "Beach", "Australia"],
		img: "cairns",
	},
	{
		id: 18,
		title: "Planfait",
		date: "1st October 2017",
		url: "z3R9E8HX0qc",
		note: "Paragliding flight above Planfait near Annecy's Lake the 16th May 2017. First time flying above dents de Lanfon à 2200 m and Lanfonnet 2100 m. Glider used : Gradient Golden 4 - 24 m2",
		keyword: ["Paragliding", "France"],
		img: "annecy",
	},
	{
		id: 19,
		title: "La Herradura",
		date: "29th September 2017",
		url: "zednXBvR7wA",
		note: "Paragliding flight from La Herradura, Andalusia, Spain. +275m above the sea level until the sunset : Wind South West 15km/h just Magic.",
		keyword: ["Paragliding", "Spain"],
		img: "herradura",
	},
	{
		id: 20,
		title: "Playa Torimba",
		date: "27th September 2017",
		url: "_P_xMPDPYoE",
		note: "Paragliding flight from Torimba,  Spain. Alone with a smooth wind from North West 10km/h.",
		keyword: ["Paragliding", "Spain"],
		img: "torimba",
	},
	{
		id: 21,
		title: "Hike & Fly Savoie",
		date: "3rd November 2016",
		url: "Ps0qW7Zx8do",
		note: "3 days in Savoie with a nice team of Auvergnats. Montagne de Sulens, Grand Arc, Rocher du Vent and  Col du Pré a few Autumn hike and fly.",
		keyword: ["Paragliding", "France", "Hiking"],
		img: "alberville",
	},
	{
		id: 22,
		title: "Flying Light",
		date: "14th October 2016",
		url: "yQrS5eRMZHI",
		note: "Hike and fly festival in Saint Gervais Haute Savoie, France in October 2016. Flights from Mont Joly, Plaine joux, Nid d'Aigle, La Charme, Le Prarion.",
		keyword: ["Paragliding", "France", "Hiking"],
		img: "stgervais",
	},
	{
		id: 23,
		title: "Dune du Pilat",
		date: "29th June 2015",
		url: "Fjn_C_wRBAw",
		note: "On the way back from Lacanau, mandatory stop at the Dune du Pilat for an amazing flight.",
		keyword: ["Paragliding", "France"],
		img: "pilat",
	},
	{
		id: 24,
		title: "Taïna Beach",
		date: "27th February 2015",
		url: "Q2Ouab4B1Qw",
		note: "Snorkelling without borders at the Taïna Beach in Haïti.",
		keyword: ["Snorkelling"],
		img: "haiti",
	},
	{
		id: 25,
		title: "Jarabacoa",
		date: "11th February 2015",
		url: "AYGjtcVssxQ",
		note: "Paragliding in the DOMINICAN REPUBLIC with Hawks Paragliding. Glider : Rush 2",
		keyword: ["Paragliding"],
		img: "jara2",
	},
	{
		id: 26,
		title: "Evosges",
		date: "22th September 2014",
		url: "dM2EfKue6hc",
		note: "Spring flight in Evsoges Bugey massif, France. ",
		keyword: ["Paragliding", "France"],
		img: "evosge",
	},
	{
		id: 27,
		title: "Puy de Dôme",
		date: "22th September 2014",
		url: "7we6CbfwCVo",
		note: "Paragliding flight from the summit of Puy de Dôme in July 2014.",
		keyword: ["Paragliding", "France"],
		img: "pdd",
	},
	{
		id: 28,
		title: "Saleve",
		date: "26th June 2014",
		url: "hmURINrPdBQ",
		note: "Paragliding flight from Mont Saleve, Haute Savoie, France. Nice spot between Geneva's lake and Mont Blanc.",
		keyword: ["Paragliding", "France"],
		img: "saleve",
	},
	{
		id: 29,
		title: "Signes",
		date: "18th September 2013",
		url: "K8VU3WdQ_fU",
		note: "Paragliding flight from the summit Signes, Sainte Baume Massif, France in July 2013.",
		keyword: ["Paragliding", "France"],
		img: "signes",
	},
	{
		id: 30,
		title: "Moustier Sainte Marie",
		date: "26th August 2013",
		url: "Ja7KdayZHAA",
		note: "Paragliding flight from Moustier Sainte Marie and above Sainte Croix's lake near the wonderfull Gorge du Verdon in August 2013.",
		keyword: ["Paragliding", "France"],
		img: "moustier",
	},
	{
		id: 31,
		title: "Brunas",
		date: "4th July 2013",
		url: "3Cmhjl-XTYw",
		note: "During the 2013's Natural Games, Paragliding flight from Brunas with a nice view of the viaduc de Millau. ",
		keyword: ["Paragliding", "France"],
		img: "millau",
	},
	{
		id: 32,
		title: "La comté verte",
		date: "24th June 2013",
		url: "KpWeXYn6mDo",
		note: "Mountain Bike friendly 35km's race around Vic le Compte in 2013.",
		keyword: ["France"],
		img: "vic",
	},
]

export const FILTERS: string[] = [
	"All",
	"Australia",
	"Switzerland",
	"France",
	"Spain",
	"Road Trip",
	"Beach",
	"Birthday",
	"Paragliding",
	"Skiing",
	"Sledging",
	"Hiking",
	"Snorkelling",
	"Jahia",
]
